# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    app.security_expression_language_provider:
            class: AppBundle\ExpressionLanguage\ExpressionLanguageProvider
            tags:
                - { name: security.expression_language_provider }
